#port will be taken from docker external port
#server:
#  port: 8081

spring:
  application:
    name: STUDENT-DOCKER

#  datasource:
#    url: jdbc:mySql://localhost:3306/studentcrud
#    username: root
#    password: wiley

  datasource:
    url: jdbc:mySql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/studentcrud?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:wiley}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#      vm options -> -DMYSQL_USER=root -DMYSQL_PASSWORD=wiley -DMYSQL_PORT=3306


#terminal commands -
#
# inside our spring boot project (where docker file is presnt
#docker images
#
#  docker build -t springboot-student-docker .








